FROM openresty/openresty:1.27.1.2-4-bookworm-fat
COPY nginx-lua-prometheus-0.20240525-1.rockspec /tmp/

RUN apt update && apt install -y git luarocks perl libmaxminddb0 libmaxminddb-dev mmdb-bin && \
    luarocks install /tmp/nginx-lua-prometheus-0.20240525-1.rockspec && \
    luarocks install lua-resty-http && \
    luarocks install lua-resty-openssl && \
    opm get anjia0532/lua-resty-maxminddb
RUN ldconfig
COPY app /app
# COPY config/nginx.dev.conf /usr/local/openresty/nginx/conf/nginx.conf
