{
 "title": "TLSCDN",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(tlscdn_nginx_http_requests_total{job=\"tlscdn-openresty\"},cdn_namespace)"
    }
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(tlscdn_nginx_http_requests_total{cdn_namespace=\"$namespace\"},cdn_gateway)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(tlscdn_nginx_http_requests_total{cdn_namespace=\"$namespace\", cdn_gateway=\"$gateway\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(tlscdn_nginx_http_requests_total{cdn_namespace=\"$namespace\", cdn_gateway=\"$gateway\", job=\"tlscdn-openresty\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS per status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status) (rate(tlscdn_nginx_http_requests_total{cdn_namespace=\"$namespace\", cdn_gateway=\"$gateway\", job=\"tlscdn-openresty\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cache HIT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(sum(rate(tlscdn_nginx_http_cache_status_total{cdn_namespace=\"$namespace\", cdn_gateway=\"$gateway\", job=\"tlscdn-openresty\", status=\"HIT\"}[$__rate_interval])) * 100) or 0 / (sum(rate(tlscdn_nginx_http_cache_status_total{cdn_namespace=\"$namespace\", cdn_gateway=\"$gateway\", job=\"tlscdn-openresty\"}[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  rate(\n    tlscdn_nginx_http_cache_status_total{\n      cdn_namespace=\"$namespace\",\n      cdn_gateway=\"$gateway\",\n      status=\"HIT\"\n    }[$__rate_interval]\n  )\n) or 0\n/\nsum(\n  rate(\n    tlscdn_nginx_http_cache_status_total{\n      cdn_namespace=\"$namespace\",\n      cdn_gateway=\"$gateway\"\n    }[$__rate_interval]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}